### ISSUE TITLE
Fundmylaptop CD (frontend)

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-FE#123]
Continous integration(CI) for FML

**Comment by anubabajide** [comment]
![image](https://user-images.githubusercontent.com/46856621/86309833-89790900-bc14-11ea-9893-b5766eb828fc.png)
![image](https://user-images.githubusercontent.com/46856621/86309855-94cc3480-bc14-11ea-8a3c-99c4cf7a7d28.png)
