### ISSUE TITLE
Contact US Page - Form Validation

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-FE#13]
As a User, my contact form should be validated before submission
Note: You would be making the contact page form fully validated so you would have to wait for the contact page desktop version to be done before you start.
https://www.figma.com/file/GTUbHki3xDCA4YWHrZ6gjl/Fund-My-Laptop-Project?node-id=2%3A0

**Comment by aalole** [comment]
Thank you.. I'm on it.

**Comment by aalole** [comment]
Hello there, I'm done with the validation,
Here id the hosted url
https://aalole.github.io/validation-testing/src/contact-us-desktop.html

waiting for you to merge the main contact-us page

**Comment by aalole** [comment]
please send a DM on slack to give go ahead. Thanks
