### ISSUE TITLE
Signup Page - UI- Mobile and Tablet

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-FE#15]
As a User, I Should be able to sign up on my mobile device
https://www.figma.com/file/GTUbHki3xDCA4YWHrZ6gjl/Fund-My-Laptop-Project?node-id=4%3A273

**Comment by St80ene** [comment]
I will love to work on issue Signup Page - UI - Mobile and Tablet #15

**Comment by emmaxyz90** [comment]
Can I work on this, would deliver in 5hours

**Comment by epospiky** [comment]
Sorry guys. I've already been assigned the task
