### ISSUE TITLE
Signup Page - Form Validation

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-FE#16]
As a User, My Signup form should be validated before submission
https://www.figma.com/file/GTUbHki3xDCA4YWHrZ6gjl/Fund-My-Laptop-Project?node-id=2%3A143

**Comment by localServer2112** [comment]
Can i get assigned to this please?
I can deliver.

**Comment by oluwakamiyeayan** [comment]
No one is assigned yet? Can I pick this up?

**Comment by emmaxyz90** [comment]
Can I be assigned this task?

**Comment by epospiky** [comment]
Sorry guys I've already been assigned the task

**Comment by oluwakamiyeayan** [comment]
Is alright
