### ISSUE TITLE
Terms and Conditions - Desktop

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-FE#30]
As a User, I Should be able to see a T&C's Page
@ulomau @vrrayz 
You two should work together to provide this design, One should make a pr while the other pull the changes and makes her own pr for evidence
https://www.figma.com/file/GTUbHki3xDCA4YWHrZ6gjl/Fund-My-Laptop-Project?node-id=86%3A3

**Comment by ulomau** [comment]
Recieved. Will use issue #30 to commit now

Uloma
