### ISSUE TITLE
FML Investor Dashboard - mobile and Tablet

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-FE#47]
As an Investor i should see a dashboard after i login on my mobile device
https://www.figma.com/file/9OgK5fqImrcCzhrLuqyITH/FML-Investor-Dashboard?node-id=0%3A1

**Comment by kaf-lamed-beyt** [comment]
Here, I'm @git on the spreadsheet

**Comment by kaf-lamed-beyt** [comment]
I've submitted a new [Pull Request](https://github.com/hngi/Fund-My-Laptop-FE/pull/143) for the dashboard. 

Kindly take a look at it.
