### ISSUE TITLE
FML Campaign Page

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-FE#48]
As a User, I should see a campaign page
@temofedev @Vchuks  you both are to work together to implement this design
Since you were paired,Discuss among your self the sections to be done. 1 person makes a PR first then the other pulls completes the work and then makes another PR
https://www.figma.com/file/WfY2g6MrxxGvfsQlpEQVbT/FML-Isaac-s-Desktop-Campaign-page?node-id=0%3A1

**Comment by Vchuks** [comment]
i have seen it
