### ISSUE TITLE
Login Page - UI - Mobile and Tablet

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-FE#66]
As a User, I Should be able to Login via a login page on my mobile device
https://www.figma.com/file/GTUbHki3xDCA4YWHrZ6gjl/Fund-My-Laptop-Project?node-id=4%3A180

**Comment by Joshuafolorunsho** [comment]
On it chief

**Comment by Joshuafolorunsho** [comment]
![image](https://user-images.githubusercontent.com/55793353/86197827-1f962c00-bb4e-11ea-83d3-2dc04be725c8.png)
this was a mistake. Please reassign me back. Making a pull request in a few minutes
