### ISSUE TITLE
FML Investee Dashboard - Ui - Desktop

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-FE#69]
As an Investee i should see a dashboard after i login
@ejiroghene15 @harobedsuip 
You two are working together to implement this design
1 person would make a PR first then the other pulls completes the work and then makes another PR, please there must be 2 Prs for evidence
https://www.figma.com/file/hx7uCuarR8VQSGBPJrTo7t/FML-Investor-Dashboard-(Copy)?node-id=0%3A1

**Comment by harobedsuip** [comment]
seen @Debbie
